### ISSUE TITLE
Pricing page

### ISSUE THREAD

**Issue by klokan** [klokantech/www.iiifserver.com#3]
| Free public service* | Standard license | Profi license |
| :-: | :-: | :-: |
| 1749 + 299/year | 3499 + 999/year | Contact us |

`*` required: open-access, no-passwords, no-login restrictions, no selling of images, no profit, no watermarks.

License for one server (virtual or physical). Contact us for multi-server licensing or redistribution rights.

License does not contain support plan. See details in [Support](Support)

There is also “Free” - use the software legally for any purpose - with IIIFServer.com watermark.

(? Maybe in FastSpring:)
- Do you already have a Kakadu license for your organisation? Get 50% discount on the initial purchase! + Form to submit us the type of license and the identifier.
- Payment by credit-card. Payment by invoice possible only for prepaid maintenance for 5 years. - maybe in FastSpring?)

**Comment by daliborjanak** [comment]
Already deployed
