### ISSUE TITLE
Support page

### ISSUE THREAD

**Issue by klokan** [klokantech/www.iiifserver.com#4]
IIIFServer is actively developed and updated on regular basis (several releases per year).
Customer with active maintenance receive email notification for new releases, with a list of fixed security bugs, information about updated software libraries and new features.

New features can be developed on request and released under open-source license.
We can act as partners on European or national research projects.

Free Community support is available via public mailing-lists. Commercial support available on request or in a form of prepaid hours.

**Comment by daliborjanak** [comment]
Already deployed
